apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nginx
spec:
  selector:
    matchLabels:
      run: app-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: app-nginx
    spec:
      containers:
      - name: app-nginx
        image: docker.io/jocatalin/kubernetes-bootcamp:v1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app-nginx
  labels:
    run: app-nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: app-nginx

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testing-app
spec:
  ingressClassName: nginx
  rules:
  - host: letsautomate.argocd.com
    http:
      paths:
      - path: /k8s
        pathType: Prefix
        backend:
          service:
            name: app-nginx
            port:
              number: 8080
